name: ota_string
description: A new Flutter project.
version: 0.0.4
homepage: https://github.com/aldychris/ota_string/tree/master/ota_string
repository: https://github.com/aldychris/ota_string/tree/master/ota_string

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
